```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#knitr::opts_knit$set(root.dir = "D:/202512-dev-seq-analyses/")

source("data_import.R")

```

```{r}
library("geomorph")
library("dplyr")
options(rgl.useNULL=TRUE)
library("rgl")
library("tidyverse")
library("gtools")
library(lubridate)
library(gridExtra)
library(factoextra)
library(ggplot2)
library(clustvarsel)
library(mclust)
library(ggpubr)
library(svglite)

#new package
# devtools::install_github("millacarmona/morphospace")
library(morphospace)
library(geomorph)
library(Morpho)
# devtools::install_github("MomX/Momocs")
library(Momocs)
library(magrittr)
library(rgl)
```


# Import data file


```{r}
# df <- readRDS("/Volumes/Yinghui/202603-dev-seq-analysis/data/202510-dev-seq-v6.rds")
#df <- readRDS("D:/202603-dev-seq-analysis/data/202510-dev-seq-v6.rds")

#files <- c("D:/202603-dev-seq-analysis/data/202510-dev-seq-v6.rds", "D:/202603-dev-seq-analysis/data/202509-dev-seq-v6.rds")

files <- c("/Volumes/Yinghui/202603-dev-seq-analysis/data/202510-dev-seq-v6.rds", "/Volumes/Yinghui/202603-dev-seq-analysis/data/202509-dev-seq-v6.rds")

df <- lapply(files, readRDS) %>% bind_rows()
```

Make sure the landmarks used is the same as the df_gmm_export
```{r}
#df_NoLA <- readRDS("/Volumes/Yinghui/202603-dev-seq-analysis/data/df_NoLA.rds")
df_gmm_export<- readRDS("/Volumes/Yinghui/202603-dev-seq-analysis/data/df_gmm_export.rds")

```

```{r}
df <- df %>%
  mutate(
    date_string = str_extract(basename(file), "^\\d{4}"),
    date_obj = ymd(paste0("2025", date_string))
  ) %>%
  select(-date_string)
```

```{r}
df_matched <- inner_join(
  df, 
  df_gmm_export, 
  by = c("date_obj", "temp", "ind","biorep")
)
```

```{r}
# convert the lm to matrix for each file.
specs_list <- df_matched %>%
  group_by(temp, biorep, ind, plane, file) %>%
  group_map(~ {
    id <- .y$file
    # Create a sub-list for this specific identifier
    spec <- list(
      matrix = as.matrix(.x[, c("X", "Y")]),
      metadata = as.list(.y)
    )
    setNames(list(spec), id)
  }) %>%
  flatten()
```

```{r}
# add lm 13 in the TA plane
specs_list<-add_lm13(specs_list)
```

# Morphospace example

```{r}
# Load tail data
data("tails")

shape_test <- tails$shapes
spp <- tails$data$species
wf <- tails$links
phy <- tails$tree

# Generate morphospace
mspace(shape_test, links = wf, cex.ldm = 5)

# Get mean shapes of each species
spp_shapes <- expected_shapes(shapes = tails$shapes, x = tails$data$species)

# Generate morphospace and project:
msp <- mspace(shapes = shape_test, links = wf, cex.ldm = 5) %>% 
  # scatter points
  proj_shapes(shapes = shape_test, col = spp) %>% 
  # convex hulls enclosing groups
  proj_groups(shapes = shape_test, groups = spp, alpha = 0.5) %>%
  # phylogenetic relationships
    proj_phylogeny(shapes = spp_shapes, tree = phy, lwd = 1.5, 
                 col.tips = match(phy$tip.label, levels(spp)))

# Plot PC1 against log-size, add legend
plot_mspace(msp, x = tails$sizes, axes = 1, nh = 6, nv = 6, cex.ldm = 4, 
            alpha.groups = 0.5, col.points = spp, col.groups = 1:nlevels(spp), 
            phylo = FALSE, xlab = "Log-size", legend = TRUE)

```
# GM

## OA
```{r}
oa_idx <- sapply(specs_list, function(x) {
  x$metadata$plane == "OA"
})

# Filter the list to keep only those specimens
oa_list <- specs_list[oa_idx]

# Extract just the 'matrix' part from every list element
# This creates a list of 2D matrices
oa_m <- lapply(oa_list, function(x) x$matrix)

# Combine them into a 3D Array
# Dimensions will be [Landmarks, Coordinates, Specimens]
# In your case: [8, 2, n]
oa_3d_array <- simplify2array(oa_m)

# (Optional) Assign specimen names to the 3rd dimension for tracking
# dimnames(oa_3d_array)[[3]] <- names(format_filtered)

# Check the final structure
dim(oa_3d_array)
```
### GPA
```{r}
gpaOA <- gpagen(oa_3d_array)
plotAllSpecimens(gpaOA$coords)
```
### morphospace

```{r}
rm(msp,shapes)
# Rename shapes dimension names to simple sequential numbers ("1", "2", ...)
dimnames(gpaOA$coords)[[3]] <- as.character(1:dim(gpaOA$coords)[3])

# Extract shapes again to apply the changes
shapes <- gpaOA$coords
# the links: TBL, ATCL, AECL, PW
lks <- list(c(2,3),c(4,5), c(6,7), c(1,8))
stage <- as.factor(df_gmm_export$stage)
cluster <- as.factor(df_gmm_export$cluster_shape)
#stage <- factor(stage, levels = c("cydippid", "early_transition", "late_transition", "lobate"))
sizes <- log(df_gmm_export$BL)

svglite("/Volumes/Yinghui/202603-dev-seq-analysis/fig/OA_lm_and_PCA.svg", width = 9, height = 7)
# Generate morphospace

msp<- mspace(shapes = shapes, links = lks, cex.ldm = 5) %>% 
  # scatter points
  proj_shapes(shapes = shapes, col = cluster) %>% 
  # convex hulls enclosing groups
  proj_groups(shapes = shapes, groups = cluster, alpha = 0.2, legend = TRUE, col = palette5[1:3])

plot_mspace(msp, nh = 6, nv = 6, legend = TRUE)
dev.off()

```

```{r}
svglite("/Volumes/Yinghui/202603-dev-seq-analysis/fig/OA_lm_and_PC1_allometric.svg", width = 9, height = 7)
# Build morphospace first
msp <- mspace(shapes = shapes, links = lks, cex.ldm = 5, plot = FALSE) %>% 
  #proj_shapes(shapes = shapes, col = stage) %>%
  proj_groups(shapes = shapes, groups = cluster, alpha = 0.2)

# Plot PC1 against log-size, add legend
plot_mspace(msp, x = sizes, axes = 1, nh = 6, nv = 6, cex.ldm = 4,
            col.points = cluster, col.groups = 1:nlevels(cluster), xlab = "Log-size",
            legend = TRUE)
dev.off()
```

```{r}

# Assign the specimen/sample names from shapes to your sizes vector
names(sizes) <- dimnames(shapes)[[3]]  # Use rownames(shapes) if shapes is a matrix

# Run 2B Partial Least Squares for shape data
pls <- pls_shapes(shapes = shapes, X = sizes)


svglite("/Volumes/Yinghui/202603-dev-seq-analysis/fig/OA_lm_and_allometric_axis.svg", width = 7, height = 7)
#allometrix axis
mspace(shapes = shapes, links = lks, cex.ldm = 5, nh = 6, nv = 6) %>% 
 proj_axis( obj = pls,lwd = 3, col = 1, 
            type = 2, axis = 1)
dev.off()
```


## TA
```{r}
ta_idx <- sapply(specs_list, function(x) {
  x$metadata$plane == "TA"
})

# Filter the list to keep only those specimens
ta_list <- specs_list[ta_idx]

# Extract just the 'matrix' part from every list element
# This creates a list of 2D matrices
ta_m <- lapply(ta_list, function(x) x$matrix)

# Combine them into a 3D Array
# Dimensions will be [Landmarks, Coordinates, Specimens]
# In your case: [8, 2, n]
ta_3d_array <- simplify2array(ta_m)

# (Optional) Assign specimen names to the 3rd dimension for tracking
# dimnames(oa_3d_array)[[3]] <- names(format_filtered)

# Check the final structure
dim(ta_3d_array)
```

### GPA
```{r}
gpaTA <- gpagen(ta_3d_array)
plotAllSpecimens(gpaTA$coords)
```

### TA without lobe landmarks
with landmarks 6,7 related to lobe removed 
```{r}
ta_final_points <- ta_3d_array[c(13,8,9,3,4,5,10,11,12,1,2) , ,]
gpaTA_2 <- gpagen(ta_final_points)
```

### morphospace
```{r}
rm(msp,shapes)
# Rename shapes dimension names to simple sequential numbers ("1", "2", ...)
dimnames(gpaOA$coords)[[3]] <- as.character(1:dim(gpaOA$coords)[3])

# Extract shapes again to apply the changes
shapes <- gpaTA_2$coords
# the links: PL+BL, TATB, TABW, TCL
lks <- list(c(1,4,5), c(6,7), c(2,3), c(4,6))
stage <- as.factor(df_gmm_export$stage)
#stage <- factor(stage, levels = c("cydippid", "early_transition", "late_transition", "lobate"))
sizes <- log(df_gmm_export$BL)

svglite("/Volumes/Yinghui/202603-dev-seq-analysis/fig/TA_lm_and_PCA.svg", width = 9, height = 7)
# Generate morphospace

msp<- mspace(shapes = shapes, links = lks, cex.ldm = 5) %>% 
  # scatter points
  proj_shapes(shapes = shapes, col = cluster) %>% 
  # convex hulls enclosing groups
  proj_groups(shapes = shapes, groups = cluster, alpha = 0.2, legend = TRUE)

plot_mspace(msp, nh = 6, nv = 6, legend = TRUE)
dev.off()

```

```{r}
svglite("/Volumes/Yinghui/202603-dev-seq-analysis/fig/TA_lm_and_PC1_allometric.svg", width = 9, height = 7)
# Build morphospace first
msp <- mspace(shapes = shapes, links = lks, cex.ldm = 5, plot = FALSE) %>% 
  #proj_shapes(shapes = shapes, col = stage) %>%
  proj_groups(shapes = shapes, groups = cluster, alpha = 0.2)

# Plot PC1 against log-size, add legend
plot_mspace(msp, x = sizes, axes = 1, nh = 6, nv = 6, cex.ldm = 4,
            col.points = cluster, col.groups = 1:nlevels(cluster), xlab = "Log-size",
            legend = TRUE)
dev.off()
```

```{r}

# Assign the specimen/sample names from shapes to your sizes vector
names(sizes) <- dimnames(shapes)[[3]]  # Use rownames(shapes) if shapes is a matrix

# Run 2B Partial Least Squares for shape data
pls <- pls_shapes(shapes = shapes, X = sizes)


svglite("/Volumes/Yinghui/202603-dev-seq-analysis/fig/TA_lm_and_allometric_axis.svg", width = 7, height = 7)
#allometrix axis
mspace(shapes = shapes, links = lks, cex.ldm = 5, nh = 6, nv = 6) %>% 
 proj_axis( obj = pls,lwd = 3, col = 1, 
            type = 2, axis = 1)
dev.off()
```

## PA
```{r}
pa_idx <- sapply(specs_list, function(x) {
  x$metadata$plane == "PA"
})

# Filter the list to keep only those specimens
pa_list <- specs_list[pa_idx]

# Extract just the 'matrix' part from every list element
# This creates a list of 2D matrices
pa_m <- lapply(pa_list, function(x) x$matrix)

# Combine them into a 3D Array
# Dimensions will be [Landmarks, Coordinates, Specimens]
# In your case: [8, 2, n]
pa_3d_array <- simplify2array(pa_m)

# (Optional) Assign specimen names to the 3rd dimension for tracking
# dimnames(oa_3d_array)[[3]] <- names(format_filtered)

# Check the final structure
dim(pa_3d_array)
```

### GPA
```{r}
gpaPA <- gpagen(pa_3d_array)
plotAllSpecimens(gpaPA$coords)
```

### PA without auricle landmarks
with landmarks 6,7 related to lobe removed 
```{r}
pa_final_points <- pa_3d_array[c(3,4,5,6,7,8) , ,]
gpaPA_2 <- gpagen(pa_final_points)
```
### morphospace

```{r}
rm(msp,shapes)
# Rename shapes dimension names to simple sequential numbers ("1", "2", ...)
#dimnames(gpaOA$coords)[[3]] <- as.character(1:dim(gpaOA$coords)[3])

# Extract shapes again to apply the changes
shapes <- gpaPA_2$coords
# the links: ATCL, AECL, PABW
lks <- list(c(1,5),c(3,6),c(2,4))
stage <- as.factor(df_gmm_export$stage)
#stage <- factor(stage, levels = c("cydippid", "early_transition", "late_transition", "lobate"))
sizes <- log(df_gmm_export$BL)

svglite("/Volumes/Yinghui/202603-dev-seq-analysis/fig/PA_lm_and_PCA.svg", width = 9, height = 7)
# Generate morphospace

msp<- mspace(shapes = shapes, links = lks, cex.ldm = 5) %>% 
  # scatter points
  proj_shapes(shapes = shapes, col = cluster) %>% 
  # convex hulls enclosing groups
  proj_groups(shapes = shapes, groups = cluster, alpha = 0.2, legend = TRUE)

plot_mspace(msp, nh = 6, nv = 6, legend = TRUE)
dev.off()

```

```{r}
svglite("/Volumes/Yinghui/202603-dev-seq-analysis/fig/PA_lm_and_PC1_allometric.svg", width = 9, height = 7)
# Build morphospace first
msp <- mspace(shapes = shapes, links = lks, cex.ldm = 5, plot = FALSE) %>% 
  #proj_shapes(shapes = shapes, col = stage) %>%
  proj_groups(shapes = shapes, groups = cluster, alpha = 0.2)

# Plot PC1 against log-size, add legend
plot_mspace(msp, x = sizes, axes = 1, nh = 6, nv = 6, cex.ldm = 4,
            col.points = cluster, col.groups = 1:nlevels(cluster), xlab = "Log-size",
            legend = TRUE)
dev.off()
```

```{r}

# Assign the specimen/sample names from shapes to your sizes vector
names(sizes) <- dimnames(shapes)[[3]]  # Use rownames(shapes) if shapes is a matrix

# Run 2B Partial Least Squares for shape data
pls <- pls_shapes(shapes = shapes, X = sizes)


svglite("/Volumes/Yinghui/202603-dev-seq-analysis/fig/PA_lm_and_allometric_axis.svg", width = 7, height = 7)
#allometrix axis
mspace(shapes = shapes, links = lks, cex.ldm = 5, nh = 6, nv = 6) %>% 
 proj_axis( obj = pls,lwd = 3, col = 1, 
            type = 2, axis = 1)
dev.off()
```
