---
title: "202512_morph_lm"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#knitr::opts_knit$set(root.dir = "D:/202512-dev-seq-analyses/")

source("data_import.R")
source("PA_measurement.R")
source("TA_measurement.R")
source("OA_measurement.R")
```

```{r}
library("geomorph")
library("dplyr")
options(rgl.useNULL=TRUE)
library("rgl")
library("tidyverse")
library("gtools")
library(lubridate)
library(gridExtra)
library(factoextra)
library(ggplot2)
library(clustvarsel)
library(mclust)
library(ggpubr)
library(svglite)

library(randomForest)
library(caret)
```

Import the dataframe created in the load_dataframe.rmd
```{r}
df_lm <- readRDS("/Volumes/Yinghui/202603-dev-seq-analysis/data/df_lm.rds")
df_lmw <- readRDS("/Volumes/Yinghui/202603-dev-seq-analysis/data/df_lmw.rds")
df_iso <- readRDS("/Volumes/Yinghui/202603-dev-seq-analysis/data/df_iso.rds")
df_gmm_export <- readRDS("/Volumes/Yinghui/202603-dev-seq-analysis/data/df_gmm_export.rds")
```


# Random forest

Example:
```{r}

data(iris)

# split data
set.seed(42)

trainIndex <- sample(1:nrow(iris), 0.8 * nrow(iris))

trainData <- iris[trainIndex, ]
testData <- iris[-trainIndex, ]

# train model
rf_model <- randomForest(Species ~ ., data = trainData)
print(rf_model)
```

Evaluate the model:
```{r}
library(caret)
predictions <- predict(rf_model, testData)
confusionMatrix(predictions, testData$Species)

# Hyperparameter Tuning
#ntree: The number of trees to grow in the forest. A higher number of trees usually results in better performance.
#mtry: The number of features to consider for each split. Tuning this parameter can help achieve a better balance between bias and variance.
rf_tuned <- randomForest(Species ~ ., data = trainData, ntree = 500, mtry = 2)
print(rf_tuned)
```

result intepretation
```{r}
importance(rf_model)
varImpPlot(rf_model)
```

# with ctenophore dataset

```{r}
set.seed(42)
df_input <- df_gmm_export[,c(20:32,34)]
df_input$stage <- as.factor(df_input$stage)
df_input <- df_input[,-9]
trainIndex <- sample(1:nrow(df_input), 0.8 * nrow(df_input))

trainData <- df_input[trainIndex, ]
testData <- df_input[-trainIndex, ]
```

## model fitting
```{r}
rf_model <- randomForest(stage ~ ., data = trainData)
print(rf_model)
```

## model fitting
```{r}
predictions <- predict(rf_model, testData)
confusionMatrix(predictions, testData$stage)
```

## Hyperparameter tuning

```{r}
rf_tuned <- randomForest(stage ~ ., data = trainData, ntree = 1000)
print(rf_tuned)
```

## result interpretation
```{r}
importance(rf_model)

svglite("/Volumes/Yinghui/202603-dev-seq-analysis/fig/Random_forest_importance.svg", width = 7, height = 7)
varImpPlot(rf_model)
dev.off()

```

