---
title: "202512_morph_lm"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#knitr::opts_knit$set(root.dir = "D:/202512-dev-seq-analyses/")

source("data_import.R")

```

```{r}
library("geomorph")
library("dplyr")
options(rgl.useNULL=TRUE)
library("rgl")
library("tidyverse")
library("gtools")
library(lubridate)
library(gridExtra)
library(factoextra)
library(ggplot2)
library(clustvarsel)
library(mclust)
library(ggpubr)
library(svglite)
```


# Import data file

```{r}

```

# Plot setting
```{r}
palette1 <- c("#343434","#A3CEF1","#3880ba","#224f73","#000000","#CCCAC2","#837D72","#ede7da")
```


### plot allometric dev

Using body length as the x axis
only focusing on the 20C group
```{r}
df_lmw <- df_lm %>%
  dplyr::select(-c(plane, log_value)) %>%
  group_by(sample_id, ind) %>%
  pivot_wider(
    names_from = measure_name,
    values_from = value
  ) 

```
plot by individual

## plot all measurements together on body length
```{r}
p1 <- ggplot(df_lmw, aes(x = BL, y = TABW)) +
  geom_smooth( linewidth = 1) +
  geom_point()
p1

p2 <- ggplot(df_lmw, aes(x = BL, y = AW)) +
  geom_smooth(linewidth = 1) +
  geom_point(aes(color = sample_id))+
  theme(legend.position = "none")
p2

p3 <- ggplot(df_lmw, aes(x = BL, y = PABW)) +
  geom_smooth(linewidth = 1) +
  geom_point()
p3

p4 <- ggplot(df_lmw, aes(x = BL, y = AEAC)) +
  geom_smooth( linewidth = 1) +
  geom_point()
p4

p5 <- ggplot(df_lmw, aes(x = BL, y = AECL)) +
  geom_smooth(linewidth = 1) +
  geom_point()
p5

p6 <- ggplot(df_lmw, aes(x = BL, y = ATAC)) +
  geom_smooth(linewidth = 1) +
  geom_point()
p6

p7 <- ggplot(df_lmw, aes(x = BL, y = ATCL)) +
  geom_smooth(linewidth = 1) +
  geom_point()
p7

p8 <- ggplot(df_lmw, aes(x = BL, y = LL)) +
  geom_smooth( linewidth = 1) +
  geom_point()
p8

p9 <- ggplot(df_lmw, aes(x = BL, y = LTM)) +
  geom_smooth( linewidth = 1) +
  geom_point()
p9

p10 <- ggplot(df_lmw, aes(x = BL, y = PL)) +
  geom_smooth(linewidth = 1) +
  geom_point()
p10

p11 <- ggplot(df_lmw, aes(x = BL, y = PW)) +
  geom_smooth(linewidth = 1) +
  geom_point()
p11

p12 <- ggplot(df_lmw, aes(x = BL, y = TATB)) +
  geom_smooth(linewidth = 1) +
  geom_point()
p12

p13 <- ggplot(df_lmw, aes(x = BL, y = TBL)) +
  geom_smooth(linewidth = 1) +
  geom_point()
p13

p14 <- ggplot(df_lmw, aes(x = BL, y = TCL)) +
  geom_smooth(linewidth = 1) +
  geom_point()
p14

```

pharynx length
```{r}
p10 <- ggplot(df_lmw, aes(x = BL, y = PL)) +
  geom_smooth(linewidth = 1) +
  stat_regline_equation(label.x=0.3, label.y=7)+
  stat_cor(aes(label=..rr.label..),label.x=0.3, label.y=6.5)+
  geom_point()+
  theme_classic()
p10
ggsave(file="/Volumes/Yinghui/202603-dev-seq-analysis/fig/PL_vs_BL.svg", plot=p10)
```

## plot all measurements together on body width by log
```{r}
p1 <- ggplot(df_lmw, aes(x = log(TABW), y = log(BL))) +
  geom_smooth(method = "lm", linewidth = 1) +
  geom_point()
p1

p2 <- ggplot(df_lmw, aes(x = log(TABW), y = log(AW))) +
  geom_smooth(method = "lm", linewidth = 1) +
  geom_point()
p2

p3 <- ggplot(df_lmw, aes(x = log(TABW), y = log(PABW))) +
  geom_smooth(method = "lm", linewidth = 1) +
  geom_point()
p3

p4 <- ggplot(df_lmw, aes(x = log(TABW), y = log(AEAC))) +
  geom_smooth(method = "lm", linewidth = 1) +
  geom_point()
p4

p5 <- ggplot(df_lmw, aes(x = log(TABW), y = log(AECL))) +
  geom_smooth(method = "lm", linewidth = 1) +
  geom_point()
p5

p6 <- ggplot(df_lmw, aes(x = log(TABW), y = log(ATAC))) +
  geom_smooth(method = "lm", linewidth = 1) +
  geom_point()
p6
p7 <- ggplot(df_lmw, aes(x = log(TABW), y = log(ATCL))) +
  geom_smooth(method = "lm", linewidth = 1) +
  geom_point()
p7

p8 <- ggplot(df_lmw, aes(x = log(TABW), y = log(LL))) +
  geom_smooth(method = "lm", linewidth = 1) +
  geom_point()
p8

p9 <- ggplot(df_lmw, aes(x = log(TABW), y = log(LTM))) +
  geom_smooth(method = "lm", linewidth = 1) +
  geom_point()
p9

p10 <- ggplot(df_lmw, aes(x = log(TABW), y = log(PL))) +
  geom_smooth(method = "lm", linewidth = 1) +
  geom_point()
p10

p11 <- ggplot(df_lmw, aes(x = log(TABW), y = log(PW))) +
  geom_smooth(method = "lm", linewidth = 1) +
  geom_point()
p11

p12 <- ggplot(df_lmw, aes(x = log(TABW), y = log(TATB))) +
  geom_smooth(method = "lm", linewidth = 1) +
  geom_point()
p12

p13 <- ggplot(df_lmw, aes(x = log(TABW), y = log(TBL))) +
  geom_smooth(method = "lm", linewidth = 1) +
  geom_point()
p13

p14 <- ggplot(df_lmw, aes(x = log(TABW), y = log(TCL))) +
  geom_smooth(method = "lm", linewidth = 1) +
  geom_point()
p14

```
## plot all measurements together on centroid

```{r}
df_lmw <- df_lmw %>% 
  mutate(centroid = (2 *(TABW/2) * (PABW/2)*BL )/3)


measure_cols <- colnames(df_lmw[,6:22])
df_iso <-  df_lmw  %>%  
  mutate(across(all_of(measure_cols), 
                ~ log(.x/centroid), 
                .names = "shape_{.col}"))
```

```{r}
p1 <- ggplot(df_iso, aes(x = log(centroid), y = log(BL))) +
  geom_smooth(method = "lm", linewidth = 1) +
  geom_point()
p1

p2 <- ggplot(df_iso, aes(x = log(centroid), y = log(AW))) +
  geom_smooth(method = "lm", linewidth = 1) +
  geom_point()
p2

p3 <- ggplot(df_iso, aes(x = log(centroid), y = log(PABW))) +
  geom_smooth(method = "lm", linewidth = 1) +
  geom_point()
p3

p4 <- ggplot(df_lmw, aes(x = log(centroid), y = log(AEAC))) +
  geom_smooth(method = "lm", linewidth = 1) +
  geom_point()
p4

p5 <- ggplot(df_lmw, aes(x = log(centroid), y = log(AECL))) +
  geom_smooth(method = "lm", linewidth = 1) +
  geom_point()
p5

p6 <- ggplot(df_lmw, aes(x = log(centroid), y = log(ATAC))) +
  geom_smooth(method = "lm", linewidth = 1) +
  geom_point()
p6
p7 <- ggplot(df_lmw, aes(x = log(centroid), y = log(ATCL))) +
  geom_smooth(method = "lm", linewidth = 1) +
  geom_point()
p7

p8 <- ggplot(df_lmw, aes(x = log(centroid), y = log(LL))) +
  geom_smooth(method = "lm", linewidth = 1) +
  geom_point()
p8

p9 <- ggplot(df_lmw, aes(x = log(centroid), y = log(LTM))) +
  geom_smooth(method = "lm", linewidth = 1) +
  geom_point()
p9

p10 <- ggplot(df_lmw, aes(x = log(centroid), y = log(PL))) +
  geom_smooth(method = "lm", linewidth = 1) +
  geom_point()
p10

p11 <- ggplot(df_lmw, aes(x = log(centroid), y = log(PW))) +
  geom_smooth(method = "lm", linewidth = 1) +
  geom_point()
p11

p12 <- ggplot(df_lmw, aes(x = log(centroid), y = log(TATB))) +
  geom_smooth(method = "lm", linewidth = 1) +
  geom_point()
p12

p13 <- ggplot(df_lmw, aes(x = log(centroid), y = log(TBL))) +
  geom_smooth(method = "lm", linewidth = 1) +
  geom_point()
p13

p14 <- ggplot(df_lmw, aes(x = log(centroid), y = log(TCL))) +
  geom_smooth(method = "lm", linewidth = 1) +
  geom_point()
p14

p15 <- ggplot(df_iso, aes(x = log(centroid), y = log(TABW))) +
  geom_smooth(method = "lm", linewidth = 1) +
  geom_point()
p15

```

```{r}
p1 <- ggplot(df_iso, aes(x = log(centroid), y = shape_BL)) +
  geom_smooth(method = "lm", linewidth = 1) +
  geom_point()
p1

p2 <- ggplot(df_iso, aes(x = log(centroid), y = shape_AW)) +
  geom_smooth(method = "lm", linewidth = 1) +
  geom_point()
p2

p3 <- ggplot(df_iso, aes(x = log(centroid), y = shape_PABW)) +
  geom_smooth(method = "lm", linewidth = 1) +
  geom_point()
p3

p4 <- ggplot(df_iso, aes(x = log(centroid), y = shape_AEAC)) +
  geom_smooth(method = "lm", linewidth = 1) +
  geom_point()
p4

p5 <- ggplot(df_iso, aes(x = log(centroid), y = shape_AECL)) +
  geom_smooth(method = "lm", linewidth = 1) +
  geom_point()
p5

p6 <- ggplot(df_iso, aes(x = log(centroid), y = shape_ATAC)) +
  geom_smooth(method = "lm", linewidth = 1) +
  geom_point()
p6
p7 <- ggplot(df_iso, aes(x = log(centroid), y = shape_ATCL)) +
  geom_smooth(method = "lm", linewidth = 1) +
  geom_point()
p7

p8 <- ggplot(df_iso, aes(x = log(centroid), y = shape_LL)) +
  geom_smooth(method = "lm", linewidth = 1) +
  geom_point()
p8

p9 <- ggplot(df_iso, aes(x = log(centroid), y = shape_LTM)) +
  geom_smooth(method = "lm", linewidth = 1) +
  geom_point()
p9

p10 <- ggplot(df_iso, aes(x = log(centroid), y = shape_PL)) +
  geom_smooth(method = "lm", linewidth = 1) +
  geom_point()
p10

p11 <- ggplot(df_iso, aes(x = log(centroid), y = shape_PW)) +
  geom_smooth(method = "lm", linewidth = 1) +
  geom_point()
p11

p12 <- ggplot(df_iso, aes(x = log(centroid), y = shape_TATB)) +
  geom_smooth(method = "lm", linewidth = 1) +
  geom_point()
p12

p13 <- ggplot(df_iso, aes(x = log(centroid), y = shape_TBL)) +
  geom_smooth(method = "lm", linewidth = 1) +
  geom_point()
p13

p14 <- ggplot(df_iso, aes(x = log(centroid), y = shape_TCL)) +
  geom_smooth(method = "lm", linewidth = 1) +
  geom_point()
p14

p15 <- ggplot(df_iso, aes(x = log(centroid), y = shape_TABW)) +
  geom_smooth(method = "lm", linewidth = 1) +
  geom_point()
p15

```

```{r}

```